Repository Jumpi96/helpo, pull requests merged in 2020-06, with the labels that each got.

#509 [RELEASE] Merging master to release v1.1.5
  .github/workflows/helpowebunits.yml
  helpo-api/actividades/management/commands/populate_db.py
  helpo-api/actividades/views.py
  helpo-api/reportes/views.py
  helpo-api/users/admin.py
  helpo-api/users/application/repositories/__init__.py
  helpo-api/users/application/repositories/organization_areas.py
  helpo-api/users/application/repositories/skills.py
  helpo-api/users/application/repositories/volunteer_profiles.py
  helpo-api/users/application/use_cases/remove_user.py
  helpo-api/users/application/use_cases/update_volunteer_profile.py
  helpo-api/users/apps.py
  helpo-api/users/domain/entities/__init__.py
  helpo-api/users/domain/entities/organization_area.py
  helpo-api/users/domain/entities/skill.py
  helpo-api/users/domain/entities/user.py
  helpo-api/users/domain/entities/volunteer_profile.py
  helpo-api/users/hex_views.py
  helpo-api/users/infrastructure/repositories/__init__.py
  helpo-api/users/infrastructure/repositories/organization_areas.py
  helpo-api/users/infrastructure/repositories/skills.py
  helpo-api/users/infrastructure/repositories/volunteer_profiles.py
  helpo-api/users/migrations/0020_auto_20200502_1330.py
  helpo-api/users/migrations/0021_auto_20200502_1334.py
  helpo-api/users/migrations/0022_auto_20200502_1409.py
  helpo-api/users/migrations/0023_auto_20200503_1350.py
  helpo-api/users/migrations/0024_auto_20200503_1848.py
  helpo-api/users/migrations/0025_auto_20200508_2126.py
  helpo-api/users/migrations/0026_remove_volunteerprofile_user.py
  helpo-api/users/models.py
  helpo-api/users/serializers.py
  helpo-api/users/tests/application/use_cases/conftest.py
  helpo-api/users/tests/application/use_cases/test_remove_user.py
  helpo-api/users/tests/domain/entities/test_user.py
  helpo-api/users/urls.py
  helpo-api/users/views.py
  helpo-web/public/index.html
  helpo-web/src/_navOrganizacion.js
  helpo-web/src/_navVoluntario.js
  helpo-web/src/containers/NoAuthLayout/NoAuthHeader.js
  helpo-web/src/routesNoAuth.js
  helpo-web/src/routesOrganizacion.js
  helpo-web/src/routesVoluntario.js
  helpo-web/src/views/Home/HomeNoAuth.js
  helpo-web/src/views/Pages/Register/Register.js
  helpo-web/src/views/Perfiles/ConsultarPerfilGenerico.js
  helpo-web/src/views/Perfiles/PerfilOrganizacion/ConsultarPerfilOrganizacion.js
  helpo-web/src/views/Perfiles/PerfilOrganizacion/ModificarPerfilOrganizacion.js
  helpo-web/src/views/Perfiles/PerfilVoluntario/ConsultarPerfilVoluntario.js
  helpo-web/src/views/Perfiles/PerfilVoluntario/ConsultarPerfilVoluntario.test.js
  helpo-web/src/views/Perfiles/PerfilVoluntario/ModificarPerfilVoluntario.js
  helpo-web/src/views/Perfiles/PerfilVoluntario/ModificarPerfilVoluntario.test.js
Labels: release

#510 Preventing my CTO from crying everytime he deploys
  deploy_helpo.sh
  deploy_helpo_aws.sh
Labels: infrastructure

#513 Fix - Back-ups
  docker-compose.local-base.aws.yml
  docker-compose.prod.yml
  helpo-api/Dockerfile
  helpo-api/backup.sh
  helpo-api/cronjobs/backup
Labels: infrastructure

#515 Hide Facebook Login
  helpo-web/src/views/Pages/Login/Login.js
  helpo-web/src/views/Pages/Register/Register.js
Labels: bug, infrastructure, mobile-to-do

#518 Modificado texto de tyc y estilo de página
  helpo-web/src/views/Pages/PageTyC/PageTyC.js
Labels: cosmetic, web

#517 v.1.2 - Mejoras esteticas finales
  helpo-web/src/_navVoluntario.js
  helpo-web/src/containers/NoAuthLayout/NoAuthHeader.js
  helpo-web/src/views/Home/HomeNoAuth.js
Labels: cosmetic

#519 [RELEASE] Merging master to release v1.2
  README.md
  deploy_helpo.sh
  deploy_helpo_aws.sh
  docker-compose.local-base.aws.yml
  helpo-api/Dockerfile
  helpo-api/actividades/management/commands/modalities.csv
  helpo-api/actividades/management/commands/populate_db.py
  helpo-api/actividades/management/commands/rubros_ong.csv
  helpo-api/actividades/management/commands/skills.csv
  helpo-api/actividades/management/commands/states.csv
  helpo-api/backup.sh
  helpo-api/cronjobs/backup
  helpo-api/requirements.txt
  helpo-api/templates/warning-email.html
  helpo-api/users/admin.py
  helpo-api/users/application/use_cases/update_volunteer_profile.py
  helpo-api/users/domain/entities/volunteer_profile.py
  helpo-api/users/infrastructure/repositories/volunteer_profiles.py
  helpo-api/users/migrations/0027_remove_volunteerprofile_dni.py
  helpo-api/users/migrations/0028_remove_volunteerprofile_work_position.py
  helpo-api/users/migrations/0029_auto_20200525_1258.py
  helpo-api/users/migrations/0030_volunteerprofile_experience.py
  helpo-api/users/models.py
  helpo-api/users/serializers.py
  helpo-api/users/urls.py
  helpo-api/users/views.py
  helpo-mobile/App/Views/Usuarios/Login.js
  helpo-web/src/_navVoluntario.js
  helpo-web/src/assets/img/home-como-funciona-converted.jpg
  helpo-web/src/assets/img/home-como-funciona.jpg
  helpo-web/src/containers/DefaultLayout/DefaultFooter.js
  helpo-web/src/containers/DefaultLayout/DefaultLayout.js
  helpo-web/src/containers/NoAuthLayout/NoAuthFooter.js
  helpo-web/src/containers/NoAuthLayout/NoAuthHeader.js
  helpo-web/src/routesEmpresa.js
  helpo-web/src/routesNoAuth.js
  helpo-web/src/routesOrganizacion.js
  helpo-web/src/routesVoluntario.js
  helpo-web/src/views/Home/HomeNoAuth.css
  helpo-web/src/views/Home/HomeNoAuth.js
  helpo-web/src/views/Pages/Login/Login.js
  helpo-web/src/views/Pages/PageTyC/PageTyC.js
  helpo-web/src/views/Pages/Register/Register.js
  helpo-web/src/views/Perfiles/ConsultarPerfilGenerico.js
  helpo-web/src/views/Perfiles/PerfilVoluntario/ConsultarPerfilVoluntario.js
  helpo-web/src/views/Perfiles/PerfilVoluntario/ModificarPerfilVoluntario.js
Labels: release

#528 v. 1.2.5 - #524 - #525 - #526
  helpo-web/src/_navOrganizacion.js
  helpo-web/src/_navVoluntario.js
  helpo-web/src/assets/img/home-como-funciona-ong-converted.jpg
  helpo-web/src/assets/img/home-como-funciona-ong.jpg
  helpo-web/src/containers/NoAuthLayout/NoAuthHeader.js
  helpo-web/src/routesNoAuth.js
  helpo-web/src/routesOrganizacion.js
  helpo-web/src/routesVoluntario.js
  helpo-web/src/views/Actividades/ConsultarColaboraciones/TablaColaboraciones/TablaColaboracion.js
  helpo-web/src/views/Actividades/ConsultarColaboraciones/TablaVoluntarios/TablaVoluntario.js
  helpo-web/src/views/Actividades/Eventos/EventoView.js
  helpo-web/src/views/Actividades/RegistrarNecesidades/RegistrarNecesidades.js
  helpo-web/src/views/Home/HomeNoAuth.js
  helpo-web/src/views/Pages/Login/Login.js
  helpo-web/src/views/Pages/Register/Register.js
  helpo-web/src/views/Perfiles/ConsultarPerfilGenerico.js
  helpo-web/src/views/Perfiles/PerfilOrganizacion/ConsultarPerfilOrganizacion.js
  helpo-web/src/views/Perfiles/PerfilOrganizacion/ModificarPerfilOrganizacion.js
  helpo-web/src/views/Perfiles/PerfilVoluntario/ConsultarPerfilVoluntario.js
  helpo-web/src/views/Suscripcion/BotonSuscripcion/BotonDesubscribir.js
  helpo-web/src/views/Suscripcion/BotonSuscripcion/ModalDesubscribir.js
  helpo-web/src/views/common/ButtonsCompartir/ButtonsCompartirEvento.js
Labels: javascript, mobile-to-do, web

#530 Feature/db backups: Backups not working
  backup_local-base_aws.sh
Labels: infrastructure

#532 N-th Fix for DB backups
  backup_local-base_aws.sh
Labels: infrastructure

#537 Cache control back to DNS level
  .gitignore
  deploy_helpo.sh
  helpo-web/nginx-staging.conf
  helpo-web/nginx.conf
Labels: infrastructure

#544 Fix bugs Perfil Organizacion
  helpo-api/users/application/use_cases/update_profile.py
  helpo-web/src/views/Perfiles/PerfilOrganizacion/ModificarPerfilOrganizacion.js
Labels: bug

#549 Closes #547 and relates to #545
  helpo-api/helpo/settings/staging_local_base.py
  helpo-web/public/index.html
Labels: infrastructure

#548 Footer corrido de lugar al regresar a página principal
  helpo-web/src/containers/DefaultLayout/DefaultLayout.js
  helpo-web/src/scss/style.css
Labels: bug

#553 Modificaciones cosméticas varias
  helpo-web/src/containers/NoAuthLayout/NoAuthFooter.js
  helpo-web/src/views/Actividades/ConsultarColaboraciones/ConsultarColaboraciones.js
  helpo-web/src/views/Home/HomeNoAuth.js
  helpo-web/src/views/Pages/Register/Register.js
  helpo-web/src/views/Perfiles/PerfilOrganizacion/ModificarPerfilOrganizacion.js
Labels: web

#555 550 - Adding more information to emails
  helpo-api/templates/ong-colaboracion-email.html
  helpo-api/templates/ong-participacion-email.html
  helpo-api/templates/was-ong-colaboracion-email.html
  helpo-api/templates/was-ong-participacion-email.html
Labels: api
